Max execution time
Codeception/robo-paracept pull request #120
Opened 2022-11-15 15:16 UTC by ccsuperstar

2022-11-18 01:41 UTC, Arhell reviewed
cc @vansari

2022-11-20 17:50 UTC, vansari commented
@ccsuperstar Thank you for your contribution. Please do not forget to write a test for your changes.

2022-11-21 09:15 UTC, ccsuperstar commented
> @ccsuperstar Thank you for your contribution. Please do not forget to write a test for your changes.

yes I will do it, then I guess I have to do tests for codeception 5 and for the previous versions

2022-12-17 19:29 UTC, vansari requested changes

2022-12-17 19:29 UTC, vansari commented on src/Merger/HtmlReportMerger.php
> +        $times = array($time1,  $time2);
```suggestion
        $times = [$time1,  $time2];
```

2023-01-02 11:46 UTC, vansari approved these changes

2023-01-02 11:47 UTC, merged